# Generated by Django 5.2.2 on 2025-06-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('req_type', models.CharField(max_length=10)),
            ],
        ),
    ]
